### ISSUE TITLE
[#0301] Configurar banco de dados: criação de tabela para estações e coletas

### ISSUE THREAD

**Issue by MariaGabrielaReis** [The-Bugger-Ducks/cloud-fox-back#1]
## Sobre a Tarefa

Configurar banco de dados, criando as tabelas necessárias para armazenar os dados das estações e coletas

#### Definition of Ready
- [x] Critério de aceite
- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Detalhes de acesso (que perfil pode acessar o que nesta tarefa)
- [x] Endpoints a serem utilizadas
- [x] Protótipo

#### Definition of Done
- [x] Testado e integrado
- [x] Sem bugs observados / review
- [x] Code review
- [x] Atende aos critérios de aceite
- [x] Documentado
- [x] Aceito pelo PO

#### Critérios de aceitação: 
- [x] Utilizar banco relacional

**Comment by ThHenrique** [comment]
Documentação:

![Image](https://user-images.githubusercontent.com/58437896/190838173-a523d85e-b73e-460c-a753-83c7129c9a5f.png)
