### ISSUE TITLE
[#0503] Documentar rota “/users” (GET)

### ISSUE THREAD

**Issue by MariaGabrielaReis** [The-Bugger-Ducks/cloud-fox-back#11]
## Sobre a Tarefa

Configurar Swagger com as informações da rota  `/stations`.
#### Definition of Ready 
- [x] Critério de aceite
- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Detalhes de acesso (que perfil pode acessar o que nesta tarefa)
- [x] Endpoints a serem utilizadas
- [x] Protótipo

#### Definition of Done 
- [x] Testado e integrado
- [x] Sem bugs observados / review
- [x] Atende aos critérios de aceite
- [x] Documentado
- [x] Aceito pelo PO

#### Critérios de aceitação: 
Conter
- [x] Response com exemplo de sucesso e erros

**Comment by ThHenrique** [comment]
#11 #9 #17 #3

![image](https://user-images.githubusercontent.com/55204419/190701313-35d6c815-8408-4868-a216-c719980cc741.png)
