### ISSUE TITLE
[#0602] Criar rota para pedido de atualização de perfil de usuário e aceite dele

### ISSUE THREAD

**Issue by MariaGabrielaReis** [The-Bugger-Ducks/cloud-fox-back#16]
## Sobre a Tarefa

Criar service, controller e rota para edição de **privilégios** de usuários (sugestão para o nome da rota: `/user/privilege/:idUser` do tipo POST)

#### Definition of Ready
- [x] Critério de aceite
- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Detalhes de acesso (que perfil pode acessar o que nesta tarefa)
- [x] Endpoints a serem utilizadas
- [x] Protótipo

#### Definition of Done
- [x] Testado e integrado
- [x] Sem bugs observados / review
- [x] Code review
- [x] Atende aos critérios de aceite
- [x] Documentado
- [x] Aceito pelo PO

#### Critérios de aceitação: 
- [x] Tratar SQL injection
- [x] Tratar erros possíveis (falta de um parâmetro no body - ex)

**Comment by ThHenrique** [comment]
> <h1>Documentação</h1>

<h2>Criação de rotas para Listagem e pedido de solicitação</h2>

- Rotas criadas:
![image](https://user-images.githubusercontent.com/80930525/190830704-7cb96651-0b06-48de-af57-a58d7930ad95.png)

- Usuário sem solicitação:
![image](https://user-images.githubusercontent.com/80930525/190831196-ee88f65c-16c1-4094-bffa-2c57d4f69a0d.png)

- Criação de solicitação:
![image](https://user-images.githubusercontent.com/80930525/190831223-18a21e1e-a7c3-43f1-9f80-fff32f1378bc.png)
![image](https://user-images.githubusercontent.com/80930525/190831615-276014f0-dba2-4d7d-9302-dacc2d259b66.png)
![image](https://user-images.githubusercontent.com/80930525/190831344-b7c95b34-592a-4640-b085-8a6557aa7810.png)


- Solicitação com mesma role:
![image](https://user-images.githubusercontent.com/80930525/190831296-2d599f0f-2a10-4acb-a668-92937d0f51f3.png)

Listagem de Solicitações:
![image](https://user-images.githubusercontent.com/80930525/190831370-6fb95486-97a6-4485-8860-af5457939038.png)
#30 

- Confirmação de role:
![image](https://user-images.githubusercontent.com/80930525/190831501-8708990c-ed66-4d9c-8813-8e72507ff25c.png)

- Deletando e alterando role em usuário:
![image](https://user-images.githubusercontent.com/80930525/190831537-af4ecf2f-5335-4ef2-acd7-47626a342007.png)
![image](https://user-images.githubusercontent.com/80930525/190831668-3dec359a-9a71-4449-aa72-a5cf2470e052.png)
