### ISSUE TITLE
[#0303] Criar rota para cadastro de estações e coletas

### ISSUE THREAD

**Issue by MariaGabrielaReis** [The-Bugger-Ducks/cloud-fox-back#2]
## Sobre a Tarefa

Criar service, controller e rota para cadastro de estações (sugestão para o nome da rota: `/stations` do tipo POST)

> Utilizar como base os dados disponíveis para cadastro no banco de dados, resultado desta task: [BACK #01](https://github.com/The-Bugger-Ducks/cloud-fox-back/issues/1)

#### Definition of Ready
- [x] Critério de aceite
- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [ ] Detalhes de acesso (que perfil pode acessar o que nesta tarefa)
~Endpoints a serem utilizadas~
~Protótipo~

#### Definition of Done
- [x] Testado e integrado
- [x] Sem bugs observados / review
- [x] Code review
- [x] Atende aos critérios de aceite
- [x] Documentado
- [x] Aceito pelo PO

#### Critérios de aceitação: 
- [x] Tratar SQL injection
- [x] Tratar erros possíveis (falta de um parâmetro no body - ex)

**Comment by ThHenrique** [comment]
Cadastro de estações e coletas:

Rotas criadas:
![image](https://user-images.githubusercontent.com/80930525/189487950-add43c8a-835c-461c-ac6c-6ed576c282a6.png)


Estação
- Cadastro 
   ![image](https://user-images.githubusercontent.com/80930525/189488066-920f4dc6-c8ed-4827-b594-c94bee3f2f3f.png)
   ![image](https://user-images.githubusercontent.com/80930525/189488100-ead20341-45e4-4dce-b7f9-dce6a2e6a601.png)

- Listagem
  ![image](https://user-images.githubusercontent.com/80930525/189488383-fcb70b2c-f914-47a3-8fd2-d756bad334b7.png)
  ![image](https://user-images.githubusercontent.com/80930525/189488550-95220fdb-eade-4033-95b6-211c9a24cba0.png)

- Deleção
  ![image](https://user-images.githubusercontent.com/80930525/189488613-26d849c2-3517-4f08-85ee-ef4699e033e0.png)
  ![image](https://user-images.githubusercontent.com/80930525/189489100-0b02ffe3-898e-414f-8de6-0685eae5af67.png)


------------------------------------

Coletas
- Cadastro
  ![image](https://user-images.githubusercontent.com/80930525/189488741-2fe95707-3db7-47f6-8f92-ab28d33c6386.png)
  ![image](https://user-images.githubusercontent.com/80930525/189489044-71e1148c-c7cb-48a7-9ecb-04c789937a59.png)


- Listagem 
  ![image](https://user-images.githubusercontent.com/80930525/189488821-c102c122-9946-4031-b906-07cfbc6e1320.png)
  ![image](https://user-images.githubusercontent.com/80930525/189488839-7ea59360-f838-49e1-a0c5-e94a06f10556.png)
  ![image](https://user-images.githubusercontent.com/80930525/189488953-6451a19b-79f0-4de7-a5b9-b622aa514f74.png)

- Deleção
  ![image](https://user-images.githubusercontent.com/80930525/189489006-1f90e716-df3e-4747-9e90-c9c761222177.png)
  ![image](https://user-images.githubusercontent.com/80930525/189489068-b35459ef-cbca-4a43-bd66-1384894f0a3d.png)
