### ISSUE TITLE
[#1002] Criar rota para visualização dos parâmetros meteorológicos

### ISSUE THREAD

**Issue by MariaGabrielaReis** [The-Bugger-Ducks/cloud-fox-back#22]
## Sobre a Tarefa

Criar service, controller e rota para visualização dos parâmetros meteorológicos (sugestão para o nome da rota: `/dashboard/report` do tipo GET)

> Utilizar como base os dados disponíveis para cadastro no banco de dados, resultado desta task: [BACK #01](https://github.com/The-Bugger-Ducks/cloud-fox-back/issues/1)

#### Definition of Ready
- [x] Critério de aceite
- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Detalhes de acesso (que perfil pode acessar o que nesta tarefa)
- [x] Endpoints a serem utilizadas
- [x] Protótipo

#### Definition of Done
- [x] Testado e integrado
- [x] Sem bugs observados / review
- [x] Code review
- [x] Atende aos critérios de aceite
- [x] Documentado
- [x] Aceito pelo PO

#### Critérios de aceitação: 
- [x] Tratar erros possíveis (falta de um parâmetro no body - ex)
- [x] A performance da consulta deve ser levada em consideração (**Pensar** em Redis)

**Comment by ThHenrique** [comment]
#22 

----------------------------------------

- [x] Criar rotas de para resgate de parâmetros de uma única estação.
- [x] Criar dinamismo quanto qual parâmetro fornecer (único)
- [x] Método para fornecer todos os parâmetros
- [ ] Método para escolher quantos parâmetros e quais fornecer, para criação de gráficos combinados. (faltante)

----------------------------------------

- [x] Método para criar estação ao receber a primeira coleta.
- [x] Rota para ativação da estação pré cadastrada 

----------------------------------------

<h1 align="center">
  <a>Documentação </a>
</h1>

### 💻 Tecnologias utilizadas:

Foram utilizadas as seguintes tecnologias durante o Desenvolvimento: Typescript, Express.js, PostgreSQL, TypeORM, VSCode, Docker.

----------------------------------------

### Tabela de Estações vazias:
![image](https://user-images.githubusercontent.com/55204419/190390442-d4ffd3d4-2a64-45b6-b6e7-edd75e192ee6.png)

----------------------------------------

### Requisição para a coleta de parametros (simulação do hardware executando o POST de uma coleta)
![image](https://user-images.githubusercontent.com/55204419/190390514-d0d53e4a-39e5-4a43-ab7d-9509f90a9611.png)

----------------------------------------

### Tabela estações populada com a nova estação (hardware se criou ao tentar enviar uma coleta)
![image](https://user-images.githubusercontent.com/55204419/190390592-0ed780c0-4cad-47b2-a280-1633f12c0864.png)

----------------------------------------

### Requisição de um admin ativando a estação para visualização WEB
![image](https://user-images.githubusercontent.com/55204419/190390630-88e546d0-169c-40cd-a929-372d77e46c71.png)

|                                                                Antes | Depois                                 |
| ------------------------------------------------------------- | :---------------------------------|
| ![image](https://user-images.githubusercontent.com/55204419/190404141-d51f754b-2df9-47cf-a884-094d969372de.png) | ![image](https://user-images.githubusercontent.com/55204419/190390679-55cce9be-40ea-4af8-9ae7-f357cf3b79cd.png)  |

----------------------------------------
#  [![](https://img.shields.io/badge/GET-2E8B57?style=for-the-badge)]() /dashboard

### Requisição de parametros de temperatura
![image](https://user-images.githubusercontent.com/55204419/190408191-d222134a-2805-43c4-b4f8-aebacb018b99.png)

### Requisição de parametros de vento
![image](https://user-images.githubusercontent.com/55204419/190408311-266252da-8b5f-4fad-ae76-260f6ab78b2d.png)

### Requisição de todos os parâmetros
![image](https://user-images.githubusercontent.com/55204419/190408357-220b723b-ee27-4074-93a4-276a8e04093f.png)
