### ISSUE TITLE
[#0509] Não listar a si próprio

### ISSUE THREAD

**Issue by MariaGabrielaReis** [The-Bugger-Ducks/cloud-fox-back#56]
## Sobre a Tarefa

Na rota de usuários avançados, não listar o usuário que está realizando a requisição

Utilizar "userId" que é adicionar na requisição ao passar pelo middware de autenticação

#### Definition of Ready
- [x] Critério de aceite
- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Detalhes de acesso (que perfil pode acessar o que nesta tarefa)
- [x] Endpoints a serem utilizadas
- [x] Protótipo

#### Definition of Done
- [x] Testado e integrado
- [x] Sem bugs observados / review
- [x] Code review
- [x] Atende aos critérios de aceite
- [x] Documentado
- [x] Aceito pelo PO

#### Critérios de aceitação: 
- [x] Seguir a regra de negócio mencionada em **sobre a tarefa**

**Comment by GabrielCamargoL** [comment]
#56 

- [x] Não listar a si próprio em listagem de usuários avançados e admins.

----------------------------------------

<h1 align="center">
  <a>Documentação </a>
</h1>

### 💻 Tecnologias utilizadas:

Foram utilizadas as seguintes tecnologias durante o Desenvolvimento: Typescript, Express.js, PostgreSQL, TypeORM, VSCode, Docker, Insomnia.

----------------------------------------
<h2 align="center">
  <a>Não listar a si próprio </a>
</h2>

### Requisição GET --> /users/advanced
Listagem de usuários avançados e administradores

#### Requisição feita pelo usuário "advanced@gmail.com"
![image](https://user-images.githubusercontent.com/55204419/198163641-a59348d9-0d34-482a-8884-99dfbab1b215.png)


Resposta da Requisição de listagem de admins e avançados para o usuário: <b>"advanced@gmail.com"</b> .
Listou apenas os usuários <b>"nancy</b> e <b>"teste"</b> .
![image](https://user-images.githubusercontent.com/55204419/198163530-705a1bc9-a498-469c-ae5f-25b938706ab5.png)
