### ISSUE TITLE
[#1504] Subir o API na AWS

### ISSUE THREAD

**Issue by MariaGabrielaReis** [The-Bugger-Ducks/cloud-fox-back#57]
## Sobre a Tarefa

Utilizar servidor disponibilizado pelo cliente na AWS para hospedar o backend do produto. Se necessário pedir suporte ao cliente

#### Definition of Ready
- [x] Critério de aceite
- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Detalhes de acesso (que perfil pode acessar o que nesta tarefa)
- [x] Endpoints a serem utilizadas
- [x] Protótipo

#### Definition of Done
- [x] Testado e integrado
- [x] Sem bugs observados / review
- [x] Code review
- [x] Atende aos critérios de aceite
- [x] Documentado
- [x] Aceito pelo PO

#### Critérios de aceitação: 
- [x] Seguir a regra de negócio mencionada em **sobre a tarefa**

**Comment by GabrielCamargoL** [comment]
<h1 align="center">
  <a>Documentação </a>
</h1>

### 💻 Tecnologias utilizadas:

Foram utilizadas as seguintes tecnologias durante o Desenvolvimento: AWS EC2, PM2, Node.js, yarn, Typescript (build)

----------------------------------------
<h2 align="center">
  <a>Subir o API na AWS </a>
</h2>

Técnica de Deploy da API no ambiente AWS EC2: **https://www.digitalocean.com/community/tutorials/how-to-set-up-a-node-js-application-for-production-on-ubuntu-20-04**

IP do servidor hospedado: **http://3.217.88.73:10000/**

![image](https://user-images.githubusercontent.com/55204419/198166681-3ff50c07-7c3e-4489-b243-97119832c900.png)


----------------------------------------

<h2 align="center">
  <a> Erros encontrados </a>
</h2>

**Erro 01:** frontend com **HTTPS** não consegue executar uma requisição em API sem **HTTPS:**
![image](https://user-images.githubusercontent.com/55204419/198166007-5a57e6f1-2cc5-4849-88a0-7f5365fdb4b2.png)

Possíveis soluções: 

1. Apresentar frontend em localhost  e usar a plataforma Netlify para estudos sobre CI/CD, pipelines e testes.
2. O cliente fornecer um certificado SSL para o projeto. Caso exista certificado grátis, verificar a veracidade da fonte.
