### ISSUE TITLE
[#2501] Criar rota para edição dos dados da estação

### ISSUE THREAD

**Issue by ThHenrique** [The-Bugger-Ducks/cloud-fox-back#60]
## Sobre a Tarefa

Criar método em service, controller e rota para edição de uma estação (sugestão para o nome da rota: `/station/:id` do tipo PUT)

> Utilizar como base os dados disponíveis para cadastro no banco de dados, resultado desta task: [BACK #01](https://github.com/The-Bugger-Ducks/cloud-fox-back/issues/1)

#### Definition of Ready
- [x] Critério de aceite
- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Detalhes de acesso (que perfil pode acessar o que nesta tarefa)
- [x] Endpoints a serem utilizadas
- [x] Protótipo

#### Definition of Done
- [x] Testado e integrado
- [x] Sem bugs observados / review
- [x] Code review
- [x] Atende aos critérios de aceite
- [x] Documentado
- [x] Aceito pelo PO

#### Critérios de aceitação: 
- [x] Funcionar

**Comment by GabrielCamargoL** [comment]
#60 [#2501]

- [x] Edição dos dados da estação.

----------------------------------------

<h1 align="center">
  <a>Documentação </a>
</h1>

### 💻 Tecnologias utilizadas:

Foram utilizadas as seguintes tecnologias durante o Desenvolvimento: Typescript, Express.js, PostgreSQL, TypeORM, VSCode, Docker, Insomnia.

----------------------------------------
<h2 align="center">
  <a>Edição dos dados da estação. </a>
</h2>

### Requisição PUT --> /stations
Edição da estação C14H

![image](https://user-images.githubusercontent.com/55204419/198163339-a164a876-53bd-489f-8fd8-bf03fd8513c7.png)

**Comment by ThHenrique** [comment]
@GabrielCamargoL aquela questão de alterarmos o macAddres (id) foi prevista nessa alteração ? @MariaGabrielaReis me lembrou desse ponto
