### ISSUE TITLE
Melhoria: atualizar funções com "TRY CATCH"

### ISSUE THREAD

**Issue by ThHenrique** [The-Bugger-Ducks/cloud-fox-back#61]
## Sobre a Tarefa

Adicionar TRY CATCH nos métodos do service e controller do backend

#### Definition of Ready
- [x] Critério de aceite
- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Detalhes de acesso (que perfil pode acessar o que nesta tarefa)
- [x] Endpoints a serem utilizadas
- [x] Protótipo

#### Definition of Done
- [x] Testado e integrado
- [x] Sem bugs observados / review
- [x] Code review
- [x] Atende aos critérios de aceite
- [x] Documentado
- [x] Aceito pelo PO

#### Critérios de aceitação: 
- [x] -

**Comment by GabrielCamargoL** [comment]
![image](https://user-images.githubusercontent.com/55204419/198592470-ba6ab198-c333-4a00-8e59-d231b3ae849e.png)
